export const restaurants = [
  { name: 'Sushi Palace', category: 'JAPANESE' },
  { name: 'Sushi Joe', category: 'JAPANESE' },
  { name: 'Sushi Street', category: 'JAPANESE' },
  { name: 'Sushi Zen', category: 'JAPANESE' },
  { name: 'Sushi Town', category: 'JAPANESE' },
  { name: 'McDonald Burger', category: 'JAPANESE' },
  { name: 'Aril Burger', category: 'MALAYSIAN' },
  { name: 'Burger Aril', category: 'MALAYSIAN' },
  { name: "Aril's Delight", category: 'MALAYSIAN' },
  { name: 'Burger Sultan', category: 'MALAYSIAN' },
  { name: 'Curry House', category: 'INDIAN' },
  { name: 'Curry Queen', category: 'INDIAN' },
  { name: 'Curry Kingdom', category: 'INDIAN' },
  { name: 'Spice Nation', category: 'INDIAN' },
  { name: 'Tandoori Bites', category: 'INDIAN' },
  { name: 'Dragon Wok', category: 'CHINESE' },
  { name: 'Wok Street', category: 'CHINESE' },
  { name: 'Golden Panda', category: 'CHINESE' },
  { name: 'Great Wall Diner', category: 'CHINESE' },
  { name: 'Beijing Bites', category: 'CHINESE' },
  { name: 'Pizza Napoli', category: 'ITALIAN' },
  { name: 'Napoli Pizza', category: 'ITALIAN' },
  { name: 'Mama Mia', category: 'ITALIAN' },
  { name: 'La Trattoria', category: 'ITALIAN' },
  { name: 'Pasta Fresca', category: 'ITALIAN' },
  { name: 'Sakura Sushi', category: 'JAPANESE' },
  { name: 'Sakura Deli', category: 'JAPANESE' },
  { name: 'Tokyo House', category: 'JAPANESE' },
  { name: 'Tokyo Table', category: 'JAPANESE' },
  { name: 'Nippon Grill', category: 'JAPANESE' },
  { name: 'Masala Magic', category: 'INDIAN' },
  { name: 'Magic Masala', category: 'INDIAN' },
  { name: 'Bombay Treats', category: 'INDIAN' },
  { name: 'Desi Spice', category: 'INDIAN' },
  { name: 'Biryani Bros', category: 'INDIAN' },
  { name: 'Dim Sum Delight', category: 'CHINESE' },
  { name: 'Sum Dim', category: 'CHINESE' },
  { name: 'Peking Chef', category: 'CHINESE' },
  { name: 'Wok & Roll', category: 'CHINESE' },
  { name: 'Rice Bowl', category: 'CHINESE' },
  { name: 'Trattoria Roma', category: 'ITALIAN' },
  { name: 'Roma Trattoria', category: 'ITALIAN' },
  { name: 'Little Italy', category: 'ITALIAN' },
  { name: 'Bella Pasta', category: 'ITALIAN' },
  { name: 'Pasta Bella', category: 'ITALIAN' },
  { name: 'Penang Flavors', category: 'MALAYSIAN' },
  { name: 'Flavors of Penang', category: 'MALAYSIAN' },
  { name: 'Nasi Lemak Street', category: 'MALAYSIAN' },
  { name: 'Roti & Satay', category: 'MALAYSIAN' },
  { name: 'Satay House', category: 'MALAYSIAN' },
  { name: 'Ramen King', category: 'JAPANESE' },
  { name: 'Udon Hub', category: 'JAPANESE' },
  { name: 'Soba Spot', category: 'JAPANESE' },
  { name: 'Ramen Ramen', category: 'JAPANESE' },
  { name: 'Donburi Den', category: 'JAPANESE' },
  { name: 'Paneer Palace', category: 'INDIAN' },
  { name: 'The Dosa Corner', category: 'INDIAN' },
  { name: 'Chili India', category: 'INDIAN' },
  { name: 'Tikka Tandoor', category: 'INDIAN' },
  { name: 'Goa Kitchen', category: 'INDIAN' },
  { name: 'Chopstick Garden', category: 'CHINESE' },
  { name: 'Wok Garden', category: 'CHINESE' },
  { name: 'Noodle Nook', category: 'CHINESE' },
  { name: 'Hotpot Heaven', category: 'CHINESE' },
  { name: 'Tea & Wok', category: 'CHINESE' },
  { name: 'Pizza Roma', category: 'ITALIAN' },
  { name: 'Pizza Express', category: 'ITALIAN' },
  { name: "Luigi's Oven", category: 'ITALIAN' },
  { name: 'The Pasta Room', category: 'ITALIAN' },
  { name: 'Fettuccine Fun', category: 'ITALIAN' },
  { name: 'Kuala Kitchen', category: 'MALAYSIAN' },
  { name: 'Langkawi Bites', category: 'MALAYSIAN' },
  { name: 'Malacca Meals', category: 'MALAYSIAN' },
  { name: 'Nasi House', category: 'MALAYSIAN' },
  { name: 'Mamak Spot', category: 'MALAYSIAN' },
  { name: 'Okonomiyaki Shack', category: 'JAPANESE' },
  { name: 'Sashimi World', category: 'JAPANESE' },
  { name: 'Katsu Corner', category: 'JAPANESE' },
  { name: 'Bento Box', category: 'JAPANESE' },
  { name: 'Tempura Ten', category: 'JAPANESE' },
  { name: 'Vindaloo Villa', category: 'INDIAN' },
  { name: 'Dilli Haat', category: 'INDIAN' },
  { name: 'Curry Junction', category: 'INDIAN' },
  { name: 'Spice Villa', category: 'INDIAN' },
  { name: 'Roti Spot', category: 'INDIAN' },
  { name: 'China Delight', category: 'CHINESE' },
  { name: 'Mandarin Eatery', category: 'CHINESE' },
  { name: 'Lotus Kitchen', category: 'CHINESE' },
  { name: 'Bamboo Garden', category: 'CHINESE' },
  { name: 'Wok Flame', category: 'CHINESE' },
  { name: 'Trattoria Milano', category: 'ITALIAN' },
  { name: 'Gnocchi Guys', category: 'ITALIAN' },
  { name: 'The Italian Job', category: 'ITALIAN' },
  { name: 'Caprese Kitchen', category: 'ITALIAN' },
  { name: 'Risotto Room', category: 'ITALIAN' },
  { name: 'Sambal House', category: 'MALAYSIAN' },
  { name: 'Mee Goreng Man', category: 'MALAYSIAN' },
  { name: 'Lemak & Co.', category: 'MALAYSIAN' },
  { name: 'Taste of Sabah', category: 'MALAYSIAN' },
  { name: 'KL Kanteen', category: 'MALAYSIAN' },
];
