export const reviews = [
  { rating: 5, reviewText: 'Absolutely loved it! The flavors were spot on.' },
  { rating: 4, reviewText: 'Great food, but the service was a bit slow.' },
  { rating: 3, reviewText: 'Average experience, nothing special.' },
  { rating: 2, reviewText: 'Food was cold and not very tasty.' },
  { rating: 1, reviewText: 'Terrible service. Would not come back.' },
  { rating: 5, reviewText: 'Exceptional dining. Will visit again!' },
  { rating: 4, reviewText: 'Tasty dishes, just a bit overpriced.' },
  { rating: 3 },
  { rating: 2 },
  { rating: 1, reviewText: 'Staff were rude and inattentive.' },
  { rating: 5 },
  { rating: 4 },
  { rating: 3 },
  { rating: 2 },
  { rating: 1 },
  { rating: 5, reviewText: 'Perfect experience from start to finish!' },
  { rating: 4, reviewText: 'Delicious but portion sizes could be better.' },
  { rating: 3, reviewText: 'Okay food, decent ambiance.' },
  { rating: 2, reviewText: 'Underwhelming food, but nice decor.' },
  { rating: 1, reviewText: 'I regret choosing this place.' },
  { rating: 5 },
  { rating: 4 },
  { rating: 3 },
  { rating: 2 },
  { rating: 1 },
  { rating: 5, reviewText: "One of the best meals I've had!" },
  { rating: 4, reviewText: 'Really good, just missed a wow factor.' },
  { rating: 3 },
  { rating: 2, reviewText: 'Too salty and took forever to arrive.' },
  { rating: 1 },
  { rating: 5, reviewText: 'Top notch service and amazing flavors.' },
  { rating: 4 },
  { rating: 3 },
  { rating: 2 },
  { rating: 1, reviewText: 'Burnt food and loud environment.' },
  { rating: 5 },
  { rating: 4 },
  { rating: 3, reviewText: 'Nothing bad, nothing great.' },
  { rating: 2 },
  { rating: 1 },
  { rating: 5, reviewText: 'Would recommend to all my friends!' },
  { rating: 4 },
  { rating: 3 },
  { rating: 2, reviewText: "Didn't live up to the hype." },
  { rating: 1 },
  { rating: 5 },
  { rating: 4, reviewText: 'Consistently good food and vibe.' },
  { rating: 3 },
  { rating: 2 },
  { rating: 1 },
  { rating: 5, reviewText: 'Fantastic presentation and flavors!' },
  { rating: 4 },
  { rating: 3 },
  { rating: 2 },
  { rating: 1, reviewText: 'Extremely disappointing.' },
  { rating: 5 },
  { rating: 4, reviewText: 'Nice setting and tasty desserts.' },
  { rating: 3 },
  { rating: 2 },
  { rating: 1 },
  { rating: 5, reviewText: 'My new favorite restaurant!' },
  { rating: 4 },
  { rating: 3, reviewText: 'It was just okay.' },
  { rating: 2 },
  { rating: 1, reviewText: "Worst food I've had in a while." },
  { rating: 5 },
  { rating: 4 },
  { rating: 3 },
  { rating: 2, reviewText: 'Not worth the price.' },
  { rating: 1 },
  { rating: 5, reviewText: 'Heavenly taste and super clean.' },
  { rating: 4, reviewText: 'Service could improve, but food was great.' },
  { rating: 3 },
  { rating: 2 },
  { rating: 1 },
  { rating: 5 },
  { rating: 4 },
  { rating: 3 },
  { rating: 2 },
  { rating: 1, reviewText: 'I won’t be coming back here.' },
  { rating: 5, reviewText: 'Fresh ingredients and wonderful staff.' },
  { rating: 4, reviewText: 'Very enjoyable experience overall.' },
  { rating: 3 },
  { rating: 2 },
  { rating: 1 },
  { rating: 5 },
  { rating: 4 },
  { rating: 3 },
  { rating: 2 },
  { rating: 1, reviewText: 'Unpleasant from start to finish.' },
  { rating: 5, reviewText: 'Incredible food and cozy vibes!' },
  { rating: 4 },
  { rating: 3 },
  { rating: 2, reviewText: 'Slow service ruined the mood.' },
  { rating: 1 },
];
