export const users = [
  {
    email: 'alice.smith@example.com',
    firstName: 'Alice',
    lastName: 'Smith',
    password: 'password123',
  },
  {
    email: 'bob.jones@example.com',
    firstName: 'Bob',
    lastName: 'Jones',
    password: 'password123',
  },
  {
    email: 'carol.white@example.com',
    firstName: 'Carol',
    lastName: 'White',
    password: 'password123',
  },
  {
    email: 'david.brown@example.com',
    firstName: 'David',
    lastName: 'Brown',
    password: 'password123',
  },
  {
    email: 'emma.taylor@example.com',
    firstName: 'Emma',
    lastName: 'Taylor',
    password: 'password123',
  },
  {
    email: 'frank.thomas@example.com',
    firstName: 'Frank',
    lastName: 'Thomas',
    password: 'password123',
  },
  {
    email: 'grace.moore@example.com',
    firstName: 'Grace',
    lastName: 'Moore',
    password: 'password123',
  },
  {
    email: 'henry.martin@example.com',
    firstName: 'Henry',
    lastName: 'Martin',
    password: 'password123',
  },
  {
    email: 'isabel.lee@example.com',
    firstName: 'Isabel',
    lastName: 'Lee',
    password: 'password123',
  },
  {
    email: 'jackson.walker@example.com',
    firstName: 'Jackson',
    lastName: 'Walker',
    password: 'password123',
  },
  {
    email: 'karen.hall@example.com',
    firstName: 'Karen',
    lastName: 'Hall',
    password: 'password123',
  },
  {
    email: 'liam.allen@example.com',
    firstName: 'Liam',
    lastName: 'Allen',
    password: 'password123',
  },
  {
    email: 'mia.young@example.com',
    firstName: 'Mia',
    lastName: 'Young',
    password: 'password123',
  },
  {
    email: 'noah.king@example.com',
    firstName: 'Noah',
    lastName: 'King',
    password: 'password123',
  },
  {
    email: 'olivia.scott@example.com',
    firstName: 'Olivia',
    lastName: 'Scott',
    password: 'password123',
  },
  {
    email: 'peter.green@example.com',
    firstName: 'Peter',
    lastName: 'Green',
    password: 'password123',
  },
  {
    email: 'quinn.baker@example.com',
    firstName: 'Quinn',
    lastName: 'Baker',
    password: 'password123',
  },
  {
    email: 'rachel.adams@example.com',
    firstName: 'Rachel',
    lastName: 'Adams',
    password: 'password123',
  },
  {
    email: 'steve.nelson@example.com',
    firstName: 'Steve',
    lastName: 'Nelson',
    password: 'password123',
  },
  {
    email: 'tina.hughes@example.com',
    firstName: 'Tina',
    lastName: 'Hughes',
    password: 'password123',
  },
  {
    email: 'ursula.edwards@example.com',
    firstName: 'Ursula',
    lastName: 'Edwards',
    password: 'password123',
  },
  {
    email: 'victor.wood@example.com',
    firstName: 'Victor',
    lastName: 'Wood',
    password: 'password123',
  },
  {
    email: 'wendy.cook@example.com',
    firstName: 'Wendy',
    lastName: 'Cook',
    password: 'password123',
  },
  {
    email: 'xander.bell@example.com',
    firstName: 'Xander',
    lastName: 'Bell',
    password: 'password123',
  },
  {
    email: 'yvonne.cooper@example.com',
    firstName: 'Yvonne',
    lastName: 'Cooper',
    password: 'password123',
  },
  {
    email: 'zachary.morgan@example.com',
    firstName: 'Zachary',
    lastName: 'Morgan',
    password: 'password123',
  },
  {
    email: 'amelia.ward@example.com',
    firstName: 'Amelia',
    lastName: 'Ward',
    password: 'password123',
  },
  {
    email: 'benjamin.kelly@example.com',
    firstName: 'Benjamin',
    lastName: 'Kelly',
    password: 'password123',
  },
  {
    email: 'chloe.brooks@example.com',
    firstName: 'Chloe',
    lastName: 'Brooks',
    password: 'password123',
  },
  {
    email: 'daniel.price@example.com',
    firstName: 'Daniel',
    lastName: 'Price',
    password: 'password123',
  },
  {
    email: 'ella.patterson@example.com',
    firstName: 'Ella',
    lastName: 'Patterson',
    password: 'password123',
  },
  {
    email: 'felix.hughes@example.com',
    firstName: 'Felix',
    lastName: 'Hughes',
    password: 'password123',
  },
  {
    email: 'gabriella.hamilton@example.com',
    firstName: 'Gabriella',
    lastName: 'Hamilton',
    password: 'password123',
  },
  {
    email: 'harvey.russell@example.com',
    firstName: 'Harvey',
    lastName: 'Russell',
    password: 'password123',
  },
  {
    email: 'ivy.griffin@example.com',
    firstName: 'Ivy',
    lastName: 'Griffin',
    password: 'password123',
  },
  {
    email: 'jason.ward@example.com',
    firstName: 'Jason',
    lastName: 'Ward',
    password: 'password123',
  },
  {
    email: 'kylie.reed@example.com',
    firstName: 'Kylie',
    lastName: 'Reed',
    password: 'password123',
  },
  {
    email: 'leo.bennett@example.com',
    firstName: 'Leo',
    lastName: 'Bennett',
    password: 'password123',
  },
  {
    email: 'madison.roberts@example.com',
    firstName: 'Madison',
    lastName: 'Roberts',
    password: 'password123',
  },
  {
    email: 'nathan.perez@example.com',
    firstName: 'Nathan',
    lastName: 'Perez',
    password: 'password123',
  },
  {
    email: 'oliver.turner@example.com',
    firstName: 'Oliver',
    lastName: 'Turner',
    password: 'password123',
  },
  {
    email: 'penelope.phillips@example.com',
    firstName: 'Penelope',
    lastName: 'Phillips',
    password: 'password123',
  },
  {
    email: 'quentin.campbell@example.com',
    firstName: 'Quentin',
    lastName: 'Campbell',
    password: 'password123',
  },
  {
    email: 'ruby.parker@example.com',
    firstName: 'Ruby',
    lastName: 'Parker',
    password: 'password123',
  },
  {
    email: 'samuel.evans@example.com',
    firstName: 'Samuel',
    lastName: 'Evans',
    password: 'password123',
  },
  {
    email: 'taylor.edwards@example.com',
    firstName: 'Taylor',
    lastName: 'Edwards',
    password: 'password123',
  },
  {
    email: 'ursula.morris@example.com',
    firstName: 'Ursula',
    lastName: 'Morris',
    password: 'password123',
  },
  {
    email: 'vincent.roberts@example.com',
    firstName: 'Vincent',
    lastName: 'Roberts',
    password: 'password123',
  },
  {
    email: 'willow.foster@example.com',
    firstName: 'Willow',
    lastName: 'Foster',
    password: 'password123',
  },
  {
    email: 'xenia.bell@example.com',
    firstName: 'Xenia',
    lastName: 'Bell',
    password: 'password123',
  },
  {
    email: 'yusuf.harrison@example.com',
    firstName: 'Yusuf',
    lastName: 'Harrison',
    password: 'password123',
  },
  {
    email: 'zoe.reynolds@example.com',
    firstName: 'Zoe',
    lastName: 'Reynolds',
    password: 'password123',
  },
  {
    email: 'alex.gray@example.com',
    firstName: 'Alex',
    lastName: 'Gray',
    password: 'password123',
  },
  {
    email: 'bella.long@example.com',
    firstName: 'Bella',
    lastName: 'Long',
    password: 'password123',
  },
  {
    email: 'caleb.fisher@example.com',
    firstName: 'Caleb',
    lastName: 'Fisher',
    password: 'password123',
  },
  {
    email: 'daisy.gibson@example.com',
    firstName: 'Daisy',
    lastName: 'Gibson',
    password: 'password123',
  },
  {
    email: 'ethan.wells@example.com',
    firstName: 'Ethan',
    lastName: 'Wells',
    password: 'password123',
  },
  {
    email: 'faith.fox@example.com',
    firstName: 'Faith',
    lastName: 'Fox',
    password: 'password123',
  },
  {
    email: 'gavin.mills@example.com',
    firstName: 'Gavin',
    lastName: 'Mills',
    password: 'password123',
  },
  {
    email: 'hannah.stone@example.com',
    firstName: 'Hannah',
    lastName: 'Stone',
    password: 'password123',
  },
  {
    email: 'ian.dixon@example.com',
    firstName: 'Ian',
    lastName: 'Dixon',
    password: 'password123',
  },
  {
    email: 'julia.burke@example.com',
    firstName: 'Julia',
    lastName: 'Burke',
    password: 'password123',
  },
  {
    email: 'kevin.hart@example.com',
    firstName: 'Kevin',
    lastName: 'Hart',
    password: 'password123',
  },
  {
    email: 'lily.ross@example.com',
    firstName: 'Lily',
    lastName: 'Ross',
    password: 'password123',
  },
  {
    email: 'mason.murray@example.com',
    firstName: 'Mason',
    lastName: 'Murray',
    password: 'password123',
  },
  {
    email: 'nina.black@example.com',
    firstName: 'Nina',
    lastName: 'Black',
    password: 'password123',
  },
  {
    email: 'owen.wheeler@example.com',
    firstName: 'Owen',
    lastName: 'Wheeler',
    password: 'password123',
  },
  {
    email: 'paige.riley@example.com',
    firstName: 'Paige',
    lastName: 'Riley',
    password: 'password123',
  },
  {
    email: 'quincy.woods@example.com',
    firstName: 'Quincy',
    lastName: 'Woods',
    password: 'password123',
  },
  {
    email: 'rebecca.daniels@example.com',
    firstName: 'Rebecca',
    lastName: 'Daniels',
    password: 'password123',
  },
  {
    email: 'sean.bates@example.com',
    firstName: 'Sean',
    lastName: 'Bates',
    password: 'password123',
  },
  {
    email: 'tessa.richards@example.com',
    firstName: 'Tessa',
    lastName: 'Richards',
    password: 'password123',
  },
  {
    email: 'ulysses.palmer@example.com',
    firstName: 'Ulysses',
    lastName: 'Palmer',
    password: 'password123',
  },
  {
    email: 'violet.norman@example.com',
    firstName: 'Violet',
    lastName: 'Norman',
    password: 'password123',
  },
  {
    email: 'wayne.jordan@example.com',
    firstName: 'Wayne',
    lastName: 'Jordan',
    password: 'password123',
  },
  {
    email: 'ximena.hunter@example.com',
    firstName: 'Ximena',
    lastName: 'Hunter',
    password: 'password123',
  },
  {
    email: 'yasmin.shaw@example.com',
    firstName: 'Yasmin',
    lastName: 'Shaw',
    password: 'password123',
  },
  {
    email: 'zane.clark@example.com',
    firstName: 'Zane',
    lastName: 'Clark',
    password: 'password123',
  },
  {
    email: 'abby.owens@example.com',
    firstName: 'Abby',
    lastName: 'Owens',
    password: 'password123',
  },
  {
    email: 'brandon.ford@example.com',
    firstName: 'Brandon',
    lastName: 'Ford',
    password: 'password123',
  },
  {
    email: 'cindy.hanson@example.com',
    firstName: 'Cindy',
    lastName: 'Hanson',
    password: 'password123',
  },
  {
    email: 'derek.walsh@example.com',
    firstName: 'Derek',
    lastName: 'Walsh',
    password: 'password123',
  },
  {
    email: 'elena.jenkins@example.com',
    firstName: 'Elena',
    lastName: 'Jenkins',
    password: 'password123',
  },
  {
    email: 'freddie.simpson@example.com',
    firstName: 'Freddie',
    lastName: 'Simpson',
    password: 'password123',
  },
  {
    email: 'georgia.gonzalez@example.com',
    firstName: 'Georgia',
    lastName: 'Gonzalez',
    password: 'password123',
  },
  {
    email: 'harry.chapman@example.com',
    firstName: 'Harry',
    lastName: 'Chapman',
    password: 'password123',
  },
  {
    email: 'iris.cunningham@example.com',
    firstName: 'Iris',
    lastName: 'Cunningham',
    password: 'password123',
  },
  {
    email: 'joel.mccoy@example.com',
    firstName: 'Joel',
    lastName: 'McCoy',
    password: 'password123',
  },
  {
    email: 'kaitlyn.stevens@example.com',
    firstName: 'Kaitlyn',
    lastName: 'Stevens',
    password: 'password123',
  },
  {
    email: 'louis.fuller@example.com',
    firstName: 'Louis',
    lastName: 'Fuller',
    password: 'password123',
  },
  {
    email: 'melanie.barnes@example.com',
    firstName: 'Melanie',
    lastName: 'Barnes',
    password: 'password123',
  },
  {
    email: 'nicolas.wells@example.com',
    firstName: 'Nicolas',
    lastName: 'Wells',
    password: 'password123',
  },
  {
    email: 'opal.matthews@example.com',
    firstName: 'Opal',
    lastName: 'Matthews',
    password: 'password123',
  },
  {
    email: 'preston.ellis@example.com',
    firstName: 'Preston',
    lastName: 'Ellis',
    password: 'password123',
  },
  {
    email: 'queenie.sanders@example.com',
    firstName: 'Queenie',
    lastName: 'Sanders',
    password: 'password123',
  },
  {
    email: 'rafael.garza@example.com',
    firstName: 'Rafael',
    lastName: 'Garza',
    password: 'password123',
  },
  {
    email: 'selena.jordan@example.com',
    firstName: 'Selena',
    lastName: 'Jordan',
    password: 'password123',
  },
  {
    email: 'travis.rose@example.com',
    firstName: 'Travis',
    lastName: 'Rose',
    password: 'password123',
  },
  {
    email: 'ursula.norman@example.com',
    firstName: 'Ursula',
    lastName: 'Norman',
    password: 'password123',
  },
  {
    email: 'vivian.knight@example.com',
    firstName: 'Vivian',
    lastName: 'Knight',
    password: 'password123',
  },
  {
    email: 'warren.lane@example.com',
    firstName: 'Warren',
    lastName: 'Lane',
    password: 'password123',
  },
];
